using FacileSconti.Application.Interfaces;
using FacileSconti.Domain.Entities;
using FacileSconti.Domain.Enums;
using FacileSconti.Infrastructure.Data;
using FacileSconti.Web.Areas.Admin.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FacileSconti.Web.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = "Admin")]
public class ManagementController : Controller
{
    private readonly ApplicationDbContext _db;
    private readonly IWebHostEnvironment _webHostEnvironment;
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly IEmailService _emailService;

    public ManagementController(
        ApplicationDbContext db,
        IWebHostEnvironment webHostEnvironment,
        UserManager<ApplicationUser> userManager,
        IEmailService emailService)
    {
        _db = db;
        _webHostEnvironment = webHostEnvironment;
        _userManager = userManager;
        _emailService = emailService;
    }

    public async Task<IActionResult> Customers(CancellationToken cancellationToken)
    {
        var items = await _db.CustomerBusinesses
            .Include(x => x.OwnerUser)
            .AsNoTracking()
            .OrderBy(x => x.Name)
            .ToListAsync(cancellationToken);
        return View(items);
    }

    [HttpGet]
    public async Task<IActionResult> NewCustomer(CancellationToken cancellationToken)
    {
        var vm = new AdminCustomerFormViewModel();
        await PopulateOwnerUsersAsync(vm, null, cancellationToken);
        return View("CustomerForm", vm);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> NewCustomer(AdminCustomerFormViewModel model, CancellationToken cancellationToken)
    {
        await PopulateOwnerUsersAsync(model, model.OwnerUserId, cancellationToken);
        model.ExistingLogoPath = null;
        if (!ModelState.IsValid)
            return View("CustomerForm", model);

        string? autoGeneratedPassword = null;
        var ownerUserId = model.OwnerUserId;
        if (string.IsNullOrWhiteSpace(ownerUserId))
        {
            var existingUser = await _userManager.FindByEmailAsync(model.Email);
            if (existingUser is not null)
            {
                ownerUserId = existingUser.Id;
            }
            else
            {
                autoGeneratedPassword = GenerateTemporaryPassword();
                var generatedUser = new ApplicationUser
                {
                    UserName = model.Email,
                    Email = model.Email,
                    FirstName = "Owner",
                    LastName = model.Name,
                    UserType = UserType.Customer
                };

                var result = await _userManager.CreateAsync(generatedUser, autoGeneratedPassword);
                if (!result.Succeeded)
                {
                    foreach (var error in result.Errors)
                        ModelState.AddModelError(string.Empty, error.Description);

                    await PopulateOwnerUsersAsync(model, null, cancellationToken);
                    return View("CustomerForm", model);
                }

                await _userManager.AddToRoleAsync(generatedUser, "Customer");
                await _emailService.SendWelcomeEmailAsync(generatedUser.Email!, $"{generatedUser.FirstName} {generatedUser.LastName}", cancellationToken);
                ownerUserId = generatedUser.Id;
            }
        }

        var entity = new CustomerBusiness
        {
            Name = model.Name,
            VatNumber = model.VatNumber,
            FiscalCode = model.FiscalCode,
            Email = model.Email,
            Phone = model.Phone,
            Address = model.Address,
            City = model.City,
            Province = model.Province,
            Description = model.Description,
            LogoPath = await SaveImageAsync(model.LogoFile, "customers", cancellationToken),
            OwnerUserId = ownerUserId
        };

        _db.CustomerBusinesses.Add(entity);
        await _db.SaveChangesAsync(cancellationToken);

        TempData["Success"] = autoGeneratedPassword is null
            ? "Cliente creato con successo."
            : $"Cliente creato con successo. Account proprietario generato automaticamente con email {model.Email} e password temporanea: {autoGeneratedPassword}";
        return RedirectToAction(nameof(Customers));
    }

    [HttpGet]
    public async Task<IActionResult> EditCustomer(int id, CancellationToken cancellationToken)
    {
        var entity = await _db.CustomerBusinesses.FindAsync([id], cancellationToken);
        if (entity is null) return NotFound();

        var vm = new AdminCustomerFormViewModel
        {
            Id = entity.Id,
            Name = entity.Name,
            VatNumber = entity.VatNumber,
            FiscalCode = entity.FiscalCode,
            Email = entity.Email,
            Phone = entity.Phone,
            Address = entity.Address,
            City = entity.City,
            Province = entity.Province,
            Description = entity.Description,
            ExistingLogoPath = entity.LogoPath,
            OwnerUserId = entity.OwnerUserId
        };

        await PopulateOwnerUsersAsync(vm, entity.OwnerUserId, cancellationToken);
        return View("CustomerForm", vm);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditCustomer(AdminCustomerFormViewModel model, CancellationToken cancellationToken)
    {
        if (model.Id is null) return NotFound();

        var entity = await _db.CustomerBusinesses.FindAsync([model.Id.Value], cancellationToken);
        if (entity is null) return NotFound();

        await PopulateOwnerUsersAsync(model, model.OwnerUserId ?? entity.OwnerUserId, cancellationToken);
        model.ExistingLogoPath = entity.LogoPath;
        if (!ModelState.IsValid)
            return View("CustomerForm", model);

        if (string.IsNullOrWhiteSpace(model.OwnerUserId))
        {
            ModelState.AddModelError(nameof(model.OwnerUserId), "Seleziona un utente proprietario.");
            return View("CustomerForm", model);
        }

        entity.Name = model.Name;
        entity.VatNumber = model.VatNumber;
        entity.FiscalCode = model.FiscalCode;
        entity.Email = model.Email;
        entity.Phone = model.Phone;
        entity.Address = model.Address;
        entity.City = model.City;
        entity.Province = model.Province;
        entity.Description = model.Description;
        if (model.LogoFile is not null)
            entity.LogoPath = await SaveImageAsync(model.LogoFile, "customers", cancellationToken);
        entity.OwnerUserId = model.OwnerUserId;

        await _db.SaveChangesAsync(cancellationToken);
        TempData["Success"] = "Cliente aggiornato con successo.";
        return RedirectToAction(nameof(Customers));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteCustomer(int id, CancellationToken cancellationToken)
    {
        var entity = await _db.CustomerBusinesses.FindAsync([id], cancellationToken);
        if (entity is null) return NotFound();

        _db.CustomerBusinesses.Remove(entity);
        await _db.SaveChangesAsync(cancellationToken);
        TempData["Success"] = "Cliente eliminato.";
        return RedirectToAction(nameof(Customers));
    }

    public async Task<IActionResult> Contracts(CancellationToken cancellationToken)
    {
        var items = await _db.CustomerContracts
            .Include(x => x.CustomerBusiness)
            .Include(x => x.SubscriptionPlan)
            .AsNoTracking()
            .OrderByDescending(x => x.CreatedAt)
            .ToListAsync(cancellationToken);
        return View(items);
    }

    [HttpGet]
    public async Task<IActionResult> NewContract(CancellationToken cancellationToken)
    {
        var vm = new AdminContractFormViewModel();
        await PopulateContractDependenciesAsync(vm, cancellationToken);
        return View("ContractForm", vm);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> NewContract(AdminContractFormViewModel model, CancellationToken cancellationToken)
    {
        await PopulateContractDependenciesAsync(model, cancellationToken);
        if (!ModelState.IsValid)
            return View("ContractForm", model);

        var entity = new CustomerContract
        {
            CustomerBusinessId = model.CustomerBusinessId,
            SubscriptionPlanId = model.SubscriptionPlanId,
            StartDate = model.StartDate,
            EndDate = model.EndDate,
            Status = model.Status,
            MaxActiveCoupons = model.MaxActiveCoupons,
            MaxDownloadsPerCoupon = model.MaxDownloadsPerCoupon,
            UnlimitedCoupons = model.UnlimitedCoupons,
            UnlimitedDownloads = model.UnlimitedDownloads,
            AgreedPrice = model.AgreedPrice,
            InitialPaymentMethod = model.InitialPaymentMethod,
            AutoRenewRequested = model.AutoRenewRequested,
            AdminNotes = model.AdminNotes
        };

        _db.CustomerContracts.Add(entity);
        await _db.SaveChangesAsync(cancellationToken);
        TempData["Success"] = "Contratto creato con successo.";
        return RedirectToAction(nameof(Contracts));
    }

    [HttpGet]
    public async Task<IActionResult> EditContract(int id, CancellationToken cancellationToken)
    {
        var entity = await _db.CustomerContracts.FindAsync([id], cancellationToken);
        if (entity is null) return NotFound();

        var vm = new AdminContractFormViewModel
        {
            Id = entity.Id,
            CustomerBusinessId = entity.CustomerBusinessId,
            SubscriptionPlanId = entity.SubscriptionPlanId,
            StartDate = entity.StartDate,
            EndDate = entity.EndDate,
            Status = entity.Status,
            MaxActiveCoupons = entity.MaxActiveCoupons,
            MaxDownloadsPerCoupon = entity.MaxDownloadsPerCoupon,
            UnlimitedCoupons = entity.UnlimitedCoupons,
            UnlimitedDownloads = entity.UnlimitedDownloads,
            AgreedPrice = entity.AgreedPrice,
            InitialPaymentMethod = entity.InitialPaymentMethod,
            AutoRenewRequested = entity.AutoRenewRequested,
            AdminNotes = entity.AdminNotes
        };

        await PopulateContractDependenciesAsync(vm, cancellationToken);
        return View("ContractForm", vm);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditContract(AdminContractFormViewModel model, CancellationToken cancellationToken)
    {
        if (model.Id is null) return NotFound();

        var entity = await _db.CustomerContracts.FindAsync([model.Id.Value], cancellationToken);
        if (entity is null) return NotFound();

        await PopulateContractDependenciesAsync(model, cancellationToken);
        if (!ModelState.IsValid)
            return View("ContractForm", model);

        entity.CustomerBusinessId = model.CustomerBusinessId;
        entity.SubscriptionPlanId = model.SubscriptionPlanId;
        entity.StartDate = model.StartDate;
        entity.EndDate = model.EndDate;
        entity.Status = model.Status;
        entity.MaxActiveCoupons = model.MaxActiveCoupons;
        entity.MaxDownloadsPerCoupon = model.MaxDownloadsPerCoupon;
        entity.UnlimitedCoupons = model.UnlimitedCoupons;
        entity.UnlimitedDownloads = model.UnlimitedDownloads;
        entity.AgreedPrice = model.AgreedPrice;
        entity.InitialPaymentMethod = model.InitialPaymentMethod;
        entity.AutoRenewRequested = model.AutoRenewRequested;
        entity.AdminNotes = model.AdminNotes;

        await _db.SaveChangesAsync(cancellationToken);
        TempData["Success"] = "Contratto aggiornato con successo.";
        return RedirectToAction(nameof(Contracts));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteContract(int id, CancellationToken cancellationToken)
    {
        var entity = await _db.CustomerContracts.FindAsync([id], cancellationToken);
        if (entity is null) return NotFound();

        _db.CustomerContracts.Remove(entity);
        await _db.SaveChangesAsync(cancellationToken);
        TempData["Success"] = "Contratto eliminato.";
        return RedirectToAction(nameof(Contracts));
    }

    public async Task<IActionResult> Coupons(CancellationToken cancellationToken)
    {
        var items = await _db.Coupons
            .Include(x => x.CustomerBusiness)
            .Include(x => x.CouponCategory)
            .AsNoTracking()
            .OrderByDescending(x => x.CreatedAt)
            .ToListAsync(cancellationToken);
        return View(items);
    }

    [HttpGet]
    public async Task<IActionResult> NewCoupon(CancellationToken cancellationToken)
    {
        var vm = new AdminCouponFormViewModel();
        await PopulateCouponDependenciesAsync(vm, cancellationToken);
        return View("CouponForm", vm);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> NewCoupon(AdminCouponFormViewModel model, CancellationToken cancellationToken)
    {
        await PopulateCouponDependenciesAsync(model, cancellationToken);
        model.ExistingImages = [];
        if (!ModelState.IsValid)
            return View("CouponForm", model);

        var exists = await _db.Coupons.AnyAsync(x => x.Slug == model.Slug, cancellationToken);
        if (exists)
        {
            ModelState.AddModelError(nameof(model.Slug), "Slug già esistente.");
            return View("CouponForm", model);
        }

        var entity = new Coupon
        {
            CustomerBusinessId = model.CustomerBusinessId,
            CouponCategoryId = model.CouponCategoryId,
            Title = model.Title,
            Slug = model.Slug,
            ShortDescription = model.ShortDescription,
            FullDescription = model.FullDescription,
            OriginalPrice = model.OriginalPrice,
            DiscountedPrice = model.DiscountedPrice,
            CouponType = model.CouponType,
            Status = model.Status,
            ValidFrom = model.ValidFrom,
            ValidTo = model.ValidTo,
            MaxDownloads = model.MaxDownloads,
            IsFeatured = model.IsFeatured,
            IsBoostedInHome = model.IsBoostedInHome
        };

        _db.Coupons.Add(entity);
        await _db.SaveChangesAsync(cancellationToken);

        if (model.ImageFiles.Count > 0)
        {
            var couponImages = new List<CouponImage>();
            for (var i = 0; i < model.ImageFiles.Count; i++)
            {
                var filePath = await SaveImageAsync(model.ImageFiles[i], "coupons", cancellationToken);
                if (string.IsNullOrWhiteSpace(filePath))
                    continue;
                couponImages.Add(new CouponImage
                {
                    CouponId = entity.Id,
                    FilePath = filePath,
                    IsPrimary = i == 0
                });
            }

            _db.CouponImages.AddRange(couponImages);
            await _db.SaveChangesAsync(cancellationToken);
        }

        if (entity.Status == CouponStatus.Active)
        {
            var business = await _db.CustomerBusinesses.AsNoTracking()
                .FirstOrDefaultAsync(x => x.Id == entity.CustomerBusinessId, cancellationToken);
            if (!string.IsNullOrWhiteSpace(business?.Email))
            {
                await _emailService.SendCouponPublishedEmailAsync(
                    business.Email,
                    business.Name,
                    entity.Title,
                    entity.ValidTo,
                    cancellationToken);
            }
        }

        TempData["Success"] = "Coupon creato con successo.";
        return RedirectToAction(nameof(Coupons));
    }

    [HttpGet]
    public async Task<IActionResult> EditCoupon(int id, CancellationToken cancellationToken)
    {
        var entity = await _db.Coupons
            .Include(x => x.Images)
            .FirstOrDefaultAsync(x => x.Id == id, cancellationToken);
        if (entity is null) return NotFound();

        var vm = new AdminCouponFormViewModel
        {
            Id = entity.Id,
            CustomerBusinessId = entity.CustomerBusinessId,
            CouponCategoryId = entity.CouponCategoryId,
            Title = entity.Title,
            Slug = entity.Slug,
            ShortDescription = entity.ShortDescription,
            FullDescription = entity.FullDescription,
            OriginalPrice = entity.OriginalPrice,
            DiscountedPrice = entity.DiscountedPrice,
            CouponType = entity.CouponType,
            Status = entity.Status,
            ValidFrom = entity.ValidFrom,
            ValidTo = entity.ValidTo,
            MaxDownloads = entity.MaxDownloads,
            IsFeatured = entity.IsFeatured,
            IsBoostedInHome = entity.IsBoostedInHome,
            ExistingImages = entity.Images
                .OrderByDescending(x => x.IsPrimary)
                .ThenBy(x => x.Id)
                .Select(x => new AdminCouponImageItemViewModel
                {
                    Id = x.Id,
                    FilePath = x.FilePath,
                    IsPrimary = x.IsPrimary
                })
                .ToList()
        };

        await PopulateCouponDependenciesAsync(vm, cancellationToken);
        return View("CouponForm", vm);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditCoupon(AdminCouponFormViewModel model, CancellationToken cancellationToken)
    {
        if (model.Id is null) return NotFound();

        var entity = await _db.Coupons
            .Include(x => x.Images)
            .FirstOrDefaultAsync(x => x.Id == model.Id.Value, cancellationToken);
        if (entity is null) return NotFound();

        model.ExistingImages = entity.Images
            .OrderByDescending(x => x.IsPrimary)
            .ThenBy(x => x.Id)
            .Select(x => new AdminCouponImageItemViewModel
            {
                Id = x.Id,
                FilePath = x.FilePath,
                IsPrimary = x.IsPrimary
            })
            .ToList();

        await PopulateCouponDependenciesAsync(model, cancellationToken);
        if (!ModelState.IsValid)
            return View("CouponForm", model);

        var duplicatedSlug = await _db.Coupons.AnyAsync(x => x.Id != model.Id.Value && x.Slug == model.Slug, cancellationToken);
        if (duplicatedSlug)
        {
            ModelState.AddModelError(nameof(model.Slug), "Slug già esistente.");
            return View("CouponForm", model);
        }

        entity.CustomerBusinessId = model.CustomerBusinessId;
        entity.CouponCategoryId = model.CouponCategoryId;
        entity.Title = model.Title;
        entity.Slug = model.Slug;
        entity.ShortDescription = model.ShortDescription;
        entity.FullDescription = model.FullDescription;
        entity.OriginalPrice = model.OriginalPrice;
        entity.DiscountedPrice = model.DiscountedPrice;
        entity.CouponType = model.CouponType;
        var previousStatus = entity.Status;
        entity.Status = model.Status;
        entity.ValidFrom = model.ValidFrom;
        entity.ValidTo = model.ValidTo;
        entity.MaxDownloads = model.MaxDownloads;
        entity.IsFeatured = model.IsFeatured;
        entity.IsBoostedInHome = model.IsBoostedInHome;

        var removeIds = model.RemoveImageIds.Distinct().ToHashSet();
        if (removeIds.Count > 0)
        {
            var imagesToRemove = entity.Images.Where(x => removeIds.Contains(x.Id)).ToList();
            _db.CouponImages.RemoveRange(imagesToRemove);
        }

        if (model.ImageFiles.Count > 0)
        {
            foreach (var imageFile in model.ImageFiles)
            {
                var filePath = await SaveImageAsync(imageFile, "coupons", cancellationToken);
                if (string.IsNullOrWhiteSpace(filePath))
                    continue;
                entity.Images.Add(new CouponImage
                {
                    FilePath = filePath,
                    IsPrimary = false
                });
            }
        }

        if (entity.Images.All(x => !x.IsPrimary))
        {
            var firstImage = entity.Images.FirstOrDefault();
            if (firstImage is not null)
                firstImage.IsPrimary = true;
        }

        await _db.SaveChangesAsync(cancellationToken);

        if (previousStatus != CouponStatus.Active && entity.Status == CouponStatus.Active)
        {
            var business = await _db.CustomerBusinesses.AsNoTracking()
                .FirstOrDefaultAsync(x => x.Id == entity.CustomerBusinessId, cancellationToken);
            if (!string.IsNullOrWhiteSpace(business?.Email))
            {
                await _emailService.SendCouponPublishedEmailAsync(
                    business.Email,
                    business.Name,
                    entity.Title,
                    entity.ValidTo,
                    cancellationToken);
            }
        }

        TempData["Success"] = "Coupon aggiornato con successo.";
        return RedirectToAction(nameof(Coupons));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteCoupon(int id, CancellationToken cancellationToken)
    {
        var entity = await _db.Coupons
            .Include(x => x.Images)
            .FirstOrDefaultAsync(x => x.Id == id, cancellationToken);
        if (entity is null) return NotFound();

        if (entity.Images.Count > 0)
            _db.CouponImages.RemoveRange(entity.Images);

        _db.Coupons.Remove(entity);
        await _db.SaveChangesAsync(cancellationToken);
        TempData["Success"] = "Coupon eliminato.";
        return RedirectToAction(nameof(Coupons));
    }

    public async Task<IActionResult> Statistics(CancellationToken cancellationToken)
    {
        var customerBreakdown = await _db.CustomerBusinesses
            .AsNoTracking()
            .Select(c => new CustomerStatsItem
            {
                CustomerId = c.Id,
                CustomerName = c.Name,
                Contracts = c.Contracts.Count,
                ActiveContracts = c.Contracts.Count(x => x.Status == ContractStatus.Active),
                Coupons = c.Coupons.Count,
                ActiveCoupons = c.Coupons.Count(x => x.Status == CouponStatus.Active),
                TotalPaid = c.Contracts
                    .SelectMany(ct => ct.Payments)
                    .Where(p => p.PaymentStatus == PaymentStatus.Paid)
                    .Sum(p => (decimal?)p.Amount) ?? 0
            })
            .OrderByDescending(x => x.TotalPaid)
            .ToListAsync(cancellationToken);

        var vm = new AdminStatisticsViewModel
        {
            TotalCustomers = await _db.CustomerBusinesses.CountAsync(cancellationToken),
            TotalContracts = await _db.CustomerContracts.CountAsync(cancellationToken),
            ActiveContracts = await _db.CustomerContracts.CountAsync(x => x.Status == ContractStatus.Active, cancellationToken),
            TotalCoupons = await _db.Coupons.CountAsync(cancellationToken),
            ActiveCoupons = await _db.Coupons.CountAsync(x => x.Status == CouponStatus.Active, cancellationToken),
            TotalPayments = await _db.PaymentRecords.CountAsync(cancellationToken),
            PaidAmount = await _db.PaymentRecords.Where(x => x.PaymentStatus == PaymentStatus.Paid).SumAsync(x => (decimal?)x.Amount, cancellationToken) ?? 0,
            PendingAmount = await _db.PaymentRecords.Where(x => x.PaymentStatus == PaymentStatus.Pending).SumAsync(x => (decimal?)x.Amount, cancellationToken) ?? 0,
            CustomerBreakdown = customerBreakdown
        };

        return View(vm);
    }

    public async Task<IActionResult> Payments(CancellationToken cancellationToken)
    {
        var payments = await _db.PaymentRecords
            .AsNoTracking()
            .Include(x => x.CustomerContract)
            .ThenInclude(x => x.CustomerBusiness)
            .OrderByDescending(x => x.PaymentDate)
            .Take(200)
            .ToListAsync(cancellationToken);
        return View(payments);
    }

    [HttpGet]
    public async Task<IActionResult> Plans(int? id, CancellationToken cancellationToken)
    {
        var plans = await _db.SubscriptionPlans
            .AsNoTracking()
            .OrderBy(x => x.Name)
            .ToListAsync(cancellationToken);

        AdminPlanFormViewModel form;
        if (id.HasValue)
        {
            var selectedPlan = plans.FirstOrDefault(x => x.Id == id.Value);
            if (selectedPlan is null) return NotFound();

            form = new AdminPlanFormViewModel
            {
                Id = selectedPlan.Id,
                Name = selectedPlan.Name,
                Code = selectedPlan.Code,
                BasePrice = selectedPlan.BasePrice,
                MaxActiveCoupons = selectedPlan.MaxActiveCoupons,
                MaxDownloadsPerCoupon = selectedPlan.MaxDownloadsPerCoupon,
                UnlimitedCoupons = selectedPlan.UnlimitedCoupons,
                UnlimitedDownloads = selectedPlan.UnlimitedDownloads,
                AllowsBoost = selectedPlan.AllowsBoost,
                IsActive = selectedPlan.IsActive,
                SelectableUntil = selectedPlan.SelectableUntil
            };
        }
        else
        {
            form = new AdminPlanFormViewModel();
        }

        var vm = new AdminPlansViewModel
        {
            Plans = plans,
            Form = form
        };
        return View(vm);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> SavePlan(AdminPlansViewModel model, CancellationToken cancellationToken)
    {
        if (!ModelState.IsValid)
        {
            model.Plans = await _db.SubscriptionPlans
                .AsNoTracking()
                .OrderBy(x => x.Name)
                .ToListAsync(cancellationToken);
            return View("Plans", model);
        }

        var codeInUse = await _db.SubscriptionPlans
            .AnyAsync(x => x.Code == model.Form.Code && x.Id != model.Form.Id, cancellationToken);
        if (codeInUse)
        {
            ModelState.AddModelError("Form.Code", "Codice piano già utilizzato.");
            model.Plans = await _db.SubscriptionPlans
                .AsNoTracking()
                .OrderBy(x => x.Name)
                .ToListAsync(cancellationToken);
            return View("Plans", model);
        }

        if (model.Form.Id.HasValue)
        {
            var entity = await _db.SubscriptionPlans.FindAsync([model.Form.Id.Value], cancellationToken);
            if (entity is null) return NotFound();

            entity.Name = model.Form.Name;
            entity.Code = model.Form.Code;
            entity.BasePrice = model.Form.BasePrice;
            entity.MaxActiveCoupons = model.Form.MaxActiveCoupons;
            entity.MaxDownloadsPerCoupon = model.Form.MaxDownloadsPerCoupon;
            entity.UnlimitedCoupons = model.Form.UnlimitedCoupons;
            entity.UnlimitedDownloads = model.Form.UnlimitedDownloads;
            entity.AllowsBoost = model.Form.AllowsBoost;
            entity.IsActive = model.Form.IsActive;
            entity.SelectableUntil = model.Form.SelectableUntil;
        }
        else
        {
            var entity = new SubscriptionPlan
            {
                Name = model.Form.Name,
                Code = model.Form.Code,
                BasePrice = model.Form.BasePrice,
                MaxActiveCoupons = model.Form.MaxActiveCoupons,
                MaxDownloadsPerCoupon = model.Form.MaxDownloadsPerCoupon,
                UnlimitedCoupons = model.Form.UnlimitedCoupons,
                UnlimitedDownloads = model.Form.UnlimitedDownloads,
                AllowsBoost = model.Form.AllowsBoost,
                IsActive = model.Form.IsActive,
                SelectableUntil = model.Form.SelectableUntil
            };

            _db.SubscriptionPlans.Add(entity);
        }

        await _db.SaveChangesAsync(cancellationToken);
        TempData["Success"] = "Piano salvato correttamente.";
        return RedirectToAction(nameof(Plans));
    }
    public IActionResult Categories() => View();
    public IActionResult BusinessRequests() => View();
    public IActionResult Cms() => View();
    public IActionResult AuditLogs() => View();

    private async Task PopulateOwnerUsersAsync(AdminCustomerFormViewModel model, string? selectedOwnerId, CancellationToken cancellationToken)
    {
        var assignedOwnerIds = await _db.CustomerBusinesses
            .Where(x => x.OwnerUserId != selectedOwnerId)
            .Select(x => x.OwnerUserId)
            .ToListAsync(cancellationToken);

        model.AvailableOwnerUsers = await _db.Users
            .Where(u => u.UserType == UserType.Customer && !assignedOwnerIds.Contains(u.Id))
            .OrderBy(u => u.Email)
            .Select(u => new SelectListItem
            {
                Value = u.Id,
                Text = $"{u.Email} ({u.FirstName} {u.LastName})"
            })
            .ToListAsync(cancellationToken);
    }

    private static string GenerateTemporaryPassword()
    {
        return $"Tmp!{Guid.NewGuid():N}aA1";
    }

    private async Task PopulateContractDependenciesAsync(AdminContractFormViewModel model, CancellationToken cancellationToken)
    {
        model.AvailableCustomers = await _db.CustomerBusinesses
            .AsNoTracking()
            .OrderBy(x => x.Name)
            .Select(x => new SelectListItem(x.Name, x.Id.ToString()))
            .ToListAsync(cancellationToken);

        var today = DateOnly.FromDateTime(DateTime.UtcNow);
        model.AvailablePlans = await _db.SubscriptionPlans
            .AsNoTracking()
            .Where(x => x.IsActive && !x.IsDeleted && (x.SelectableUntil == null || x.SelectableUntil >= today))
            .OrderBy(x => x.Name)
            .Select(x => new SelectListItem($"{x.Name} ({x.BasePrice:0.00}€)", x.Id.ToString()))
            .ToListAsync(cancellationToken);
    }

    private async Task PopulateCouponDependenciesAsync(AdminCouponFormViewModel model, CancellationToken cancellationToken)
    {
        model.AvailableCustomers = await _db.CustomerBusinesses
            .AsNoTracking()
            .OrderBy(x => x.Name)
            .Select(x => new SelectListItem(x.Name, x.Id.ToString()))
            .ToListAsync(cancellationToken);

        model.AvailableCategories = await _db.CouponCategories
            .AsNoTracking()
            .OrderBy(x => x.Name)
            .Select(x => new SelectListItem(x.Name, x.Id.ToString()))
            .ToListAsync(cancellationToken);
    }

    private async Task<string?> SaveImageAsync(IFormFile? file, string folderName, CancellationToken cancellationToken)
    {
        if (file is null || file.Length == 0)
            return null;

        var extension = Path.GetExtension(file.FileName);
        var safeFileName = $"{Guid.NewGuid():N}{extension}";
        var relativePath = Path.Combine("uploads", folderName, safeFileName).Replace("\\", "/");
        var absoluteDirectory = Path.Combine(_webHostEnvironment.WebRootPath, "uploads", folderName);
        Directory.CreateDirectory(absoluteDirectory);
        var absolutePath = Path.Combine(absoluteDirectory, safeFileName);

        await using var stream = new FileStream(absolutePath, FileMode.Create);
        await file.CopyToAsync(stream, cancellationToken);
        return "/" + relativePath;
    }
}
