CREATE DATABASE FacileSconti COLLATE SQL_Latin1_General_CP1_CI_AS;
GO
USE FacileSconti;
GO

CREATE TABLE SubscriptionPlans (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(120) NOT NULL,
    Code NVARCHAR(30) NOT NULL,
    BasePrice DECIMAL(18,2) NOT NULL,
    MaxActiveCoupons INT NOT NULL,
    MaxDownloadsPerCoupon INT NULL,
    UnlimitedCoupons BIT NOT NULL DEFAULT 0,
    UnlimitedDownloads BIT NOT NULL DEFAULT 0,
    AllowsBoost BIT NOT NULL DEFAULT 0,
    SelectableUntil DATE NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    CreatedBy NVARCHAR(100) NULL,
    UpdatedBy NVARCHAR(100) NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    IsDeleted BIT NOT NULL DEFAULT 0
);

CREATE TABLE CustomerBusinesses (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL,
    VatNumber NVARCHAR(20) NOT NULL,
    FiscalCode NVARCHAR(30) NOT NULL,
    Email NVARCHAR(256) NOT NULL,
    Phone NVARCHAR(30) NOT NULL,
    Address NVARCHAR(250) NOT NULL,
    City NVARCHAR(120) NOT NULL,
    Province NVARCHAR(20) NOT NULL,
    Description NVARCHAR(1000) NULL,
    LogoPath NVARCHAR(255) NULL,
    OwnerUserId NVARCHAR(450) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NULL, CreatedBy NVARCHAR(100) NULL, UpdatedBy NVARCHAR(100) NULL,
    IsActive BIT NOT NULL DEFAULT 1, IsDeleted BIT NOT NULL DEFAULT 0
);

CREATE TABLE CouponCategories (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(120) NOT NULL,
    Slug NVARCHAR(150) NOT NULL,
    IconCss NVARCHAR(100) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NULL, CreatedBy NVARCHAR(100) NULL, UpdatedBy NVARCHAR(100) NULL,
    IsActive BIT NOT NULL DEFAULT 1, IsDeleted BIT NOT NULL DEFAULT 0
);

CREATE TABLE CustomerContracts (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CustomerBusinessId INT NOT NULL,
    SubscriptionPlanId INT NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    Status INT NOT NULL,
    MaxActiveCoupons INT NOT NULL,
    MaxDownloadsPerCoupon INT NULL,
    UnlimitedCoupons BIT NOT NULL,
    UnlimitedDownloads BIT NOT NULL,
    AgreedPrice DECIMAL(18,2) NOT NULL,
    InitialPaymentMethod INT NOT NULL,
    AutoRenewRequested BIT NOT NULL DEFAULT 0,
    AdminNotes NVARCHAR(1000) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NULL, CreatedBy NVARCHAR(100) NULL, UpdatedBy NVARCHAR(100) NULL,
    IsActive BIT NOT NULL DEFAULT 1, IsDeleted BIT NOT NULL DEFAULT 0
);

CREATE TABLE Coupons (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CustomerBusinessId INT NOT NULL,
    CouponCategoryId INT NOT NULL,
    Title NVARCHAR(200) NOT NULL,
    Slug NVARCHAR(220) NOT NULL,
    ShortDescription NVARCHAR(400) NOT NULL,
    FullDescription NVARCHAR(MAX) NOT NULL,
    OriginalPrice DECIMAL(18,2) NULL,
    DiscountedPrice DECIMAL(18,2) NULL,
    CouponType INT NOT NULL,
    Status INT NOT NULL,
    ValidFrom DATE NOT NULL,
    ValidTo DATE NOT NULL,
    MaxDownloads INT NULL,
    IsFeatured BIT NOT NULL DEFAULT 0,
    IsBoostedInHome BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NULL, CreatedBy NVARCHAR(100) NULL, UpdatedBy NVARCHAR(100) NULL,
    IsActive BIT NOT NULL DEFAULT 1, IsDeleted BIT NOT NULL DEFAULT 0
);

CREATE TABLE CouponDownloads (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    CouponId INT NOT NULL,
    EndUserId NVARCHAR(450) NOT NULL,
    UniqueCode NVARCHAR(40) NOT NULL,
    SecureToken NVARCHAR(200) NOT NULL,
    DownloadedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    IsRedeemed BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NULL, CreatedBy NVARCHAR(100) NULL, UpdatedBy NVARCHAR(100) NULL,
    IsActive BIT NOT NULL DEFAULT 1, IsDeleted BIT NOT NULL DEFAULT 0
);

CREATE TABLE CouponViews (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    CouponId INT NOT NULL,
    ViewedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    IpAddress NVARCHAR(50) NULL,
    UserAgent NVARCHAR(500) NULL
);

CREATE TABLE PaymentRecords (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    CustomerContractId INT NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    PaymentMethod INT NOT NULL,
    PaymentStatus INT NOT NULL,
    PaymentDate DATETIME2 NOT NULL,
    ExternalReference NVARCHAR(120) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NULL, CreatedBy NVARCHAR(100) NULL, UpdatedBy NVARCHAR(100) NULL,
    IsActive BIT NOT NULL DEFAULT 1, IsDeleted BIT NOT NULL DEFAULT 0
);

CREATE TABLE HomeBoostPlans (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(120) NOT NULL,
    DurationDays INT NOT NULL,
    Price DECIMAL(18,2) NOT NULL,
    Priority INT NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NULL, CreatedBy NVARCHAR(100) NULL, UpdatedBy NVARCHAR(100) NULL,
    IsActive BIT NOT NULL DEFAULT 1, IsDeleted BIT NOT NULL DEFAULT 0
);

CREATE TABLE CustomerBoostActivations (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CouponId INT NOT NULL,
    HomeBoostPlanId INT NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    Status INT NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NULL, CreatedBy NVARCHAR(100) NULL, UpdatedBy NVARCHAR(100) NULL,
    IsActive BIT NOT NULL DEFAULT 1, IsDeleted BIT NOT NULL DEFAULT 0
);

CREATE TABLE PublicPages (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Slug NVARCHAR(120) NOT NULL,
    Title NVARCHAR(250) NOT NULL,
    ContentHtml NVARCHAR(MAX) NOT NULL,
    ShowInFooter BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NULL, CreatedBy NVARCHAR(100) NULL, UpdatedBy NVARCHAR(100) NULL,
    IsActive BIT NOT NULL DEFAULT 1, IsDeleted BIT NOT NULL DEFAULT 0
);

CREATE TABLE NewsletterSubscriptions (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Email NVARCHAR(255) NOT NULL,
    IsConfirmed BIT NOT NULL DEFAULT 0,
    ConfirmedAt DATETIME2 NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NULL, CreatedBy NVARCHAR(100) NULL, UpdatedBy NVARCHAR(100) NULL,
    IsActive BIT NOT NULL DEFAULT 1, IsDeleted BIT NOT NULL DEFAULT 0
);

CREATE TABLE AuditLogs (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    ActorUserId NVARCHAR(450) NOT NULL,
    ActionType NVARCHAR(100) NOT NULL,
    EntityName NVARCHAR(120) NOT NULL,
    EntityId NVARCHAR(80) NOT NULL,
    DataBefore NVARCHAR(MAX) NULL,
    DataAfter NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
