USE FacileSconti;
GO

CREATE TABLE CustomerContacts (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CustomerBusinessId INT NOT NULL,
    FullName NVARCHAR(160) NOT NULL,
    Email NVARCHAR(256) NOT NULL,
    Phone NVARCHAR(30) NOT NULL,
    RoleName NVARCHAR(80) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NULL, CreatedBy NVARCHAR(100) NULL, UpdatedBy NVARCHAR(100) NULL,
    IsActive BIT NOT NULL DEFAULT 1, IsDeleted BIT NOT NULL DEFAULT 0
);

CREATE TABLE ContractFeatures (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    SubscriptionPlanId INT NOT NULL,
    FeatureKey NVARCHAR(80) NOT NULL,
    FeatureValue NVARCHAR(200) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NULL, CreatedBy NVARCHAR(100) NULL, UpdatedBy NVARCHAR(100) NULL,
    IsActive BIT NOT NULL DEFAULT 1, IsDeleted BIT NOT NULL DEFAULT 0
);

CREATE TABLE CouponImages (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CouponId INT NOT NULL,
    FilePath NVARCHAR(255) NOT NULL,
    AltText NVARCHAR(160) NULL,
    IsPrimary BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NULL, CreatedBy NVARCHAR(100) NULL, UpdatedBy NVARCHAR(100) NULL,
    IsActive BIT NOT NULL DEFAULT 1, IsDeleted BIT NOT NULL DEFAULT 0
);

CREATE TABLE CouponRedemptions (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    CouponDownloadId BIGINT NOT NULL,
    RedeemedAt DATETIME2 NOT NULL,
    RedeemedByOperator NVARCHAR(120) NULL,
    Notes NVARCHAR(500) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NULL, CreatedBy NVARCHAR(100) NULL, UpdatedBy NVARCHAR(100) NULL,
    IsActive BIT NOT NULL DEFAULT 1, IsDeleted BIT NOT NULL DEFAULT 0
);

CREATE TABLE CouponPaymentConfigs (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CouponId INT NOT NULL,
    PlatformFeePercentage DECIMAL(5,2) NULL,
    CurrencyCode NVARCHAR(10) NULL,
    IsOnlinePaymentEnabled BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NULL, CreatedBy NVARCHAR(100) NULL, UpdatedBy NVARCHAR(100) NULL,
    IsActive BIT NOT NULL DEFAULT 1, IsDeleted BIT NOT NULL DEFAULT 0
);
